{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.0.jar",
          "url": "VendorTools-2025.0.0.jar",
          "size": 11839,
          "sha512": "7fd3ede8bd1ddb18519e6b44fab4306111ed23b3b05a9c8b40bfec1c23debba93bccffd9294d5de9aa71f79da780181d4a8457de5347827ee1a85436f48d5751",
          "sha256": "a9822a75b6ee5b7873d3da82d41e7ca611cc561d565d15dc9447850800ffce46",
          "sha1": "f84394121cc9a6afa3112b1bf7550d0684390750",
          "md5": "fcc36cf5fc7565cfb16bb7da7e05f9b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.0.jar",
          "url": "VendorTools-2025.0.0.jar",
          "size": 11839,
          "sha512": "7fd3ede8bd1ddb18519e6b44fab4306111ed23b3b05a9c8b40bfec1c23debba93bccffd9294d5de9aa71f79da780181d4a8457de5347827ee1a85436f48d5751",
          "sha256": "a9822a75b6ee5b7873d3da82d41e7ca611cc561d565d15dc9447850800ffce46",
          "sha1": "f84394121cc9a6afa3112b1bf7550d0684390750",
          "md5": "fcc36cf5fc7565cfb16bb7da7e05f9b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.0-javadoc.jar",
          "url": "VendorTools-2025.0.0-javadoc.jar",
          "size": 98904,
          "sha512": "18ec923c118f09be86426a3a856e47898a8e46d3672bf3deb8f9b91f96fe515aeb6533ef71a553c80933e7bf37f3b70b96ad7dab9f7baf48f7d1112f952575eb",
          "sha256": "05ea6bb6a4e4af67077681fcfbdd2dace53c12d3874ac32798dd3089398e6d5f",
          "sha1": "e943f9622f19f74dbfc445d137b956b490737ee5",
          "md5": "ee003b3e0bb6948e77b8ff2fb305ef74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.0-sources.jar",
          "url": "VendorTools-2025.0.0-sources.jar",
          "size": 5473,
          "sha512": "0e66576dedd2ebbe2531b5b4d039aa2d0742a725d12e9cd8d8cbe730563c971f7b3026c5bd1509620d77a3d1b92d70ee5ec0a25565268570a4c73007c0a522d3",
          "sha256": "12745599f88ab381b4adb7e0bce18cf504e3beb21ca87d7ca2fefb944043f330",
          "sha1": "86bc0a00fd39d7eb89f14d38253d82eb0d8c08b1",
          "md5": "1c2e9029828f087867033acd90f931d8"
        }
      ]
    }
  ]
}
