{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 16859,
          "sha512": "286c784bb79cf4914b517416c45390d9341d0e4f1b8c3f5879da142fd83fbbe3f31835dd4f21165ee5df07df2f6c52608bd768e04ef5d8dc0ff3095939c91612",
          "sha256": "7b9f06fa41b0d21f4b1e2d1f7ac4134e1ea147367f35e41d62dda87635cac8f3",
          "sha1": "1fa3fde200238feffc87c1acb2c03fdc57368e81",
          "md5": "7eb6d2a076db955c0ef981c3bd5eaa32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 16859,
          "sha512": "286c784bb79cf4914b517416c45390d9341d0e4f1b8c3f5879da142fd83fbbe3f31835dd4f21165ee5df07df2f6c52608bd768e04ef5d8dc0ff3095939c91612",
          "sha256": "7b9f06fa41b0d21f4b1e2d1f7ac4134e1ea147367f35e41d62dda87635cac8f3",
          "sha1": "1fa3fde200238feffc87c1acb2c03fdc57368e81",
          "md5": "7eb6d2a076db955c0ef981c3bd5eaa32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 111896,
          "sha512": "0c3b14d2dc938f9be0ee822f9ff5010bbced269a370a3c9ff86b60ba74875202294543d57be0f4295892c941a6f256cac57cfb50300ebc19b1de33f5905f85ef",
          "sha256": "c28525857082e3ee85dd7acdb14c6ead6a25adfa4e2a80596d6a6b8715930b7f",
          "sha1": "1d07cdbac319fb2bb50596f489170bd500388479",
          "md5": "0e61022c1d4891048d9c710d3f0c5015"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 7820,
          "sha512": "3c407018cce108f372662c9e86ce63ed4cc290d51edaae5b0eab034bc3c9eddaa206e91a5c0ca6070c9bd00865fd46b1ab510cb197f7384f53458ba675ac3498",
          "sha256": "4e1c4662faeb339dc7b59ec364579bee5e8573076ae627adcb7d9ffc9efd8bfd",
          "sha1": "28c631bc819042ea019543f12522cb4071be86d1",
          "md5": "e5847f9f920ef533e558dd9befcf879a"
        }
      ]
    }
  ]
}
