{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20333,
          "sha512": "ed0b8f17efb436a044f5ddb14171b5ba7ae1f6560c4aa5d45b6333ca135ef6dff24c9bfd4807e01f8a36e83bbd965f4c275d1211649e1f3a531a91c24ce67d94",
          "sha256": "d002a83ab99a3600cb9ba83de68c6696a26901f75de0d40de79f826285a75838",
          "sha1": "b16558416d808534df5b634024c75e12a0e1e4a4",
          "md5": "59fe27595ebeb7e44de82ed7111dda45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20333,
          "sha512": "ed0b8f17efb436a044f5ddb14171b5ba7ae1f6560c4aa5d45b6333ca135ef6dff24c9bfd4807e01f8a36e83bbd965f4c275d1211649e1f3a531a91c24ce67d94",
          "sha256": "d002a83ab99a3600cb9ba83de68c6696a26901f75de0d40de79f826285a75838",
          "sha1": "b16558416d808534df5b634024c75e12a0e1e4a4",
          "md5": "59fe27595ebeb7e44de82ed7111dda45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 129405,
          "sha512": "340b6c30347c490614bd494bc84995e373fe264f5eeff7240fbb0c68da15fd14b8cc02bc87065ad70bd3bdae606649301ee287b6549a6ac65d6b3177fbc1f53f",
          "sha256": "c64432bad43b1c7c287df4fff11a3d8e1957eeb29f1af81f5b21f4ab1efa5270",
          "sha1": "ad1d396e3bbb1c04a42662e88ced26c26a41b202",
          "md5": "470d7ab124ed9abbaf4ac101b49a3cd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 9474,
          "sha512": "10fad84b0e7d2788e3d11069e339dd3497471a3f1587ce60e0b9c62dca9aa30ff7d4d1277dbb38e38782b6c4c3c90a799afe6204218a104428851bc06592cdcb",
          "sha256": "5d7742fcddb87341fbc8dc10ef191f9b1ca4d8879729ea2648a7f31406dcda3d",
          "sha1": "da8711d1161d026943e9b473600790414d7cd66e",
          "md5": "43021a025005616fce821bcc78330e88"
        }
      ]
    }
  ]
}
