{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20285,
          "sha512": "85eb8ba8c58b703cac14b1e6da2c5835fd94954532671e8aa8322d2cbdd02028d51a78e5add894950873b835e64a18c05fdc54f0648a0ede9c5840b4214aabac",
          "sha256": "3d04df1b8d44a156a034787ae0edd91761fcef1f5f5e755049649ee1588f97b1",
          "sha1": "694633b0f85fd76a94dd657b695ee4db58e478a1",
          "md5": "09f55816321955e9e2dcc189fb6df745"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20285,
          "sha512": "85eb8ba8c58b703cac14b1e6da2c5835fd94954532671e8aa8322d2cbdd02028d51a78e5add894950873b835e64a18c05fdc54f0648a0ede9c5840b4214aabac",
          "sha256": "3d04df1b8d44a156a034787ae0edd91761fcef1f5f5e755049649ee1588f97b1",
          "sha1": "694633b0f85fd76a94dd657b695ee4db58e478a1",
          "md5": "09f55816321955e9e2dcc189fb6df745"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 129405,
          "sha512": "340b6c30347c490614bd494bc84995e373fe264f5eeff7240fbb0c68da15fd14b8cc02bc87065ad70bd3bdae606649301ee287b6549a6ac65d6b3177fbc1f53f",
          "sha256": "c64432bad43b1c7c287df4fff11a3d8e1957eeb29f1af81f5b21f4ab1efa5270",
          "sha1": "ad1d396e3bbb1c04a42662e88ced26c26a41b202",
          "md5": "470d7ab124ed9abbaf4ac101b49a3cd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 9453,
          "sha512": "19a85f69da89dfbf56ac5a7b5886ab85c53a9ae32ad8532582e1f40e868a35a31818b016fbcaab9999bcc89b7e83f5a0618f28dda632bfbc5013cfa9625883a3",
          "sha256": "dcb6dcb41ccbd6f7b94c3f200397676bc01f7daec7468d0a5d3e3642ee302d4f",
          "sha1": "d86ee2ddf552b96cdfd20bd82ba90d67e5759705",
          "md5": "3c1c40c43c015c4b3b56fef2e28c2568"
        }
      ]
    }
  ]
}
