{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 11839,
          "sha512": "75186d4e045ae2d4c5cad6acf73f4a9b513f0f4aaa9658165095352399b404cd42b2c6de998f6e020afcaf18a867362242d755062741d51e77bc21b71daeea02",
          "sha256": "fdb7749f67d0de73d648a2c6efb5e222ad0eada7210398d3c6e7ec5dd97389f8",
          "sha1": "474c4f030922e8f54ecffd679cb8faafb597392a",
          "md5": "81f6ff2b931375ad24c8da4e434038b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 11839,
          "sha512": "75186d4e045ae2d4c5cad6acf73f4a9b513f0f4aaa9658165095352399b404cd42b2c6de998f6e020afcaf18a867362242d755062741d51e77bc21b71daeea02",
          "sha256": "fdb7749f67d0de73d648a2c6efb5e222ad0eada7210398d3c6e7ec5dd97389f8",
          "sha1": "474c4f030922e8f54ecffd679cb8faafb597392a",
          "md5": "81f6ff2b931375ad24c8da4e434038b1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 99021,
          "sha512": "5622caee8b34eb11d26e694ae0b771043ff04713b4f52d578fc22201ea57774e19c1588077eed7c5ab0b905b833b31d079c0813ea52dc615b9fd698749344658",
          "sha256": "29cfc1ac772e090f306ce0e22f1cac9f0d5a51e99839c3f2f30d583a3ee077c6",
          "sha1": "1c70840115010cfeaf0d2129a881b318ebed22eb",
          "md5": "e5a088f43349dbf7e201bac7362e7cff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 5473,
          "sha512": "c1aca0cefd9a82e2b9fcfaba999b1b63093f4f7fc601724c66408fd13ae9b400c7054c3eacf584cf4e137cd825a71d1aa9ed5a23534603265dca35eb248e116c",
          "sha256": "4c1263dd0fa1162139abab747f78df5522ca8b041a56e7050b6834263082642f",
          "sha1": "69711d344a1fb13ae34decb5900634ced94d6723",
          "md5": "ba253dd22efce16111efa71200695505"
        }
      ]
    }
  ]
}
