{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20525,
          "sha512": "da5a07ec8c3428d1232438c104aa50e6ca51bead2ba58e70de372c93ce02877222bcdecd38611d9a85fae4813bcec5193d605a45ee6bbcba5db15c46890b9478",
          "sha256": "e379c9cd02d50ed9a2a47a3c1b5015d63f8820b8b7be0e31d968c6212aeddd59",
          "sha1": "63e9d8b4cd854650b3cb174c7398a6b7bdf05ff0",
          "md5": "ca5d1694a866a16340853213cf75e3ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20525,
          "sha512": "da5a07ec8c3428d1232438c104aa50e6ca51bead2ba58e70de372c93ce02877222bcdecd38611d9a85fae4813bcec5193d605a45ee6bbcba5db15c46890b9478",
          "sha256": "e379c9cd02d50ed9a2a47a3c1b5015d63f8820b8b7be0e31d968c6212aeddd59",
          "sha1": "63e9d8b4cd854650b3cb174c7398a6b7bdf05ff0",
          "md5": "ca5d1694a866a16340853213cf75e3ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 129469,
          "sha512": "65ec8184fce60734684ba95eeb84807c8106a9bb8e8a852578c904f7ea606d44415843b46f1567c391944ea8beb9a3123693c3d54ef3145c5f10e61fcabc18c8",
          "sha256": "e59fd7f3597417f48afa20c54745b4a0c23f80d51903a86918504111bb17b034",
          "sha1": "a4ce3241febd1f437eead3e5b0c282ef1fa9c07d",
          "md5": "21e04c3f586c39b03292833e48911113"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 9624,
          "sha512": "a75561882c692efebd088490cf75ace392b77e6dcc48027183940e95503c506d0d6f57e9635fcf19b1f13ec09d368c130b6297e41548b827fc4c07d1fda0b844",
          "sha256": "7f674036ea5cd604df1f3898547e4463b6758e20cb8be35514c14a358636f775",
          "sha1": "20e8ccd5e739c08ce4d0789cc9240e6c807002b1",
          "md5": "f83f12fdb52175a2d8f680fa3598354b"
        }
      ]
    }
  ]
}
