{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20486,
          "sha512": "e2e48dcda00de9dac64111d9093209b8f04dd1c3ffa41790ca774a196dcb9435d4b91b5984ba6e98a19f363c6823fa2cdfecd91d2148b31ae73259547f1da543",
          "sha256": "e523e0782fed0163bab1acba943c03b87be574918a1052ca649e6cb74bd337ad",
          "sha1": "d5c0fcc3fde14835d0fc8c8c4d7ee2e6f33dfc8f",
          "md5": "9675bab98e54b246b84fd25f89e46648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20486,
          "sha512": "e2e48dcda00de9dac64111d9093209b8f04dd1c3ffa41790ca774a196dcb9435d4b91b5984ba6e98a19f363c6823fa2cdfecd91d2148b31ae73259547f1da543",
          "sha256": "e523e0782fed0163bab1acba943c03b87be574918a1052ca649e6cb74bd337ad",
          "sha1": "d5c0fcc3fde14835d0fc8c8c4d7ee2e6f33dfc8f",
          "md5": "9675bab98e54b246b84fd25f89e46648"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 129469,
          "sha512": "65ec8184fce60734684ba95eeb84807c8106a9bb8e8a852578c904f7ea606d44415843b46f1567c391944ea8beb9a3123693c3d54ef3145c5f10e61fcabc18c8",
          "sha256": "e59fd7f3597417f48afa20c54745b4a0c23f80d51903a86918504111bb17b034",
          "sha1": "a4ce3241febd1f437eead3e5b0c282ef1fa9c07d",
          "md5": "21e04c3f586c39b03292833e48911113"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 9588,
          "sha512": "12842d3daf4c667e79ff9b8e0147743ae0580a4f563a8cf98a872b96039f41190728d0702ce5a1557939feb6a60fc0a9393a5441e2b8a78a53b65dee53e0f767",
          "sha256": "5478aff11d80d3dd650153feea52be1119e15740cbbebce9f587eff92f4fcb44",
          "sha1": "9968f170b216d38b74cc3da50d972e916c509855",
          "md5": "993d76dc8bb85bc6ae2d4c78e5b22b13"
        }
      ]
    }
  ]
}
