{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 11849,
          "sha512": "2eb4fb201dc2cac7d05fe3bc753fa8a203aad266c3fea228f51c9a3c42fb5f833f9d083188b275cd07f46577a22bf9caa4c0279bc0069e2f976981ecb4636e16",
          "sha256": "8ab9db5abc14f6ff833660d48d0019c940886aef3c63c8c8444250225b92405c",
          "sha1": "803ef8d4c2e78b2f25bc29996b08fc67bb97433a",
          "md5": "e9098c0947a7783807bc56a1cddd1035"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 11849,
          "sha512": "2eb4fb201dc2cac7d05fe3bc753fa8a203aad266c3fea228f51c9a3c42fb5f833f9d083188b275cd07f46577a22bf9caa4c0279bc0069e2f976981ecb4636e16",
          "sha256": "8ab9db5abc14f6ff833660d48d0019c940886aef3c63c8c8444250225b92405c",
          "sha1": "803ef8d4c2e78b2f25bc29996b08fc67bb97433a",
          "md5": "e9098c0947a7783807bc56a1cddd1035"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 99021,
          "sha512": "5622caee8b34eb11d26e694ae0b771043ff04713b4f52d578fc22201ea57774e19c1588077eed7c5ab0b905b833b31d079c0813ea52dc615b9fd698749344658",
          "sha256": "29cfc1ac772e090f306ce0e22f1cac9f0d5a51e99839c3f2f30d583a3ee077c6",
          "sha1": "1c70840115010cfeaf0d2129a881b318ebed22eb",
          "md5": "e5a088f43349dbf7e201bac7362e7cff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 5470,
          "sha512": "e77f6727eda6e48819499adab414a35de4cd3ce25ac188de9f4846ef4734d852abf92caf5cc1d91763537a36cbb78e5e98b05b14a3f3d7c5df73968239a91ba5",
          "sha256": "507a11071152fb5fd751b8480bec2b2cd8b215e7fab3023ff80549f7c1156781",
          "sha1": "64b980824ba04d01e299fbdca771870e2b1078f4",
          "md5": "199285b6d6462e1238d765f44d9f8368"
        }
      ]
    }
  ]
}
