{
  "formatVersion": "1.1",
  "component": {
    "group": "net.apollofops",
    "module": "VendorTools",
    "version": "2025.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20466,
          "sha512": "2cb3119f7457a939f8c4ed8d2ac9a1ca80bbad88b94a42c96634d0d1527fe12836f25448f8827f74e66a27cd657ccab49dff9a6ff51ba68d899746a4cd7e78af",
          "sha256": "d95078bedc83b2b0c418d8b22d3c0fabd847062741e88e2e32dc932eef6c6f98",
          "sha1": "c124bdfcbb5b641809cdc4850a8af84f219883ad",
          "md5": "46f5a43b83fc5f8d56ae1d6c1a891b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT.jar",
          "size": 20466,
          "sha512": "2cb3119f7457a939f8c4ed8d2ac9a1ca80bbad88b94a42c96634d0d1527fe12836f25448f8827f74e66a27cd657ccab49dff9a6ff51ba68d899746a4cd7e78af",
          "sha256": "d95078bedc83b2b0c418d8b22d3c0fabd847062741e88e2e32dc932eef6c6f98",
          "sha1": "c124bdfcbb5b641809cdc4850a8af84f219883ad",
          "md5": "46f5a43b83fc5f8d56ae1d6c1a891b44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-javadoc.jar",
          "size": 129405,
          "sha512": "340b6c30347c490614bd494bc84995e373fe264f5eeff7240fbb0c68da15fd14b8cc02bc87065ad70bd3bdae606649301ee287b6549a6ac65d6b3177fbc1f53f",
          "sha256": "c64432bad43b1c7c287df4fff11a3d8e1957eeb29f1af81f5b21f4ab1efa5270",
          "sha1": "ad1d396e3bbb1c04a42662e88ced26c26a41b202",
          "md5": "470d7ab124ed9abbaf4ac101b49a3cd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "url": "VendorTools-2025.0.1-SNAPSHOT-sources.jar",
          "size": 9577,
          "sha512": "20bb28c4f564f1a7e2c20c27f4148fa95e6e801b2026f70f3f5395ca57d0709d12c182e0e8c11955480e1c715e86ce3adc702b06f1d4097fcaec707f7afa4ac2",
          "sha256": "1485a57ffc855d14c47c9a52f6eed1f52514465bb338a6fc947f0cf356fd6a20",
          "sha1": "b7e30f308ccdf2b0ffe9f30bfa9d2331f78274e1",
          "md5": "56de39014da2b2e570004a1dfc95a5d4"
        }
      ]
    }
  ]
}
