name: Update vendordep

on:
  repository_dispatch:
    types: [publish_update]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ github.event.client_payload.releaseVersion }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Clone library repository
        run: |
          gh repo clone roboblazers7617/${{ github.event.client_payload.libraryName }}

      - name: Build library
        run: ./gradlew build
        working-directory: ${{ github.event.client_payload.libraryName }}

      - name: Publish library
        run: ./gradlew publish
        working-directory: ${{ github.event.client_payload.libraryName }}
        env:
          mavenRepo: ${{ github.workspace }}/repos

      - name: Update repository
        run: |
          git config --global user.name "BlazerBot 7617"
          git config --global user.email "188250476+blazerbot-7617[bot]@users.noreply.github.com"
          git add repos/.
          git commit -m "Upgrading ${{ github.event.client_payload.libraryName }} to ${{ github.event.client_payload.releaseVersion }}"
          git push
