name: Update Maven repository and deploy

on:
  repository_dispatch:
    types: [publish_update]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ github.event.client_payload.releaseVersion }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Clone library repository
        uses: actions/checkout@v4
        with:
          repository: roboblazers7617/${{ github.event.client_payload.libraryName }}
          path: library-repository
          ref: ${{ github.event.client_payload.ref }}

      - name: Build library
        run: ./gradlew build
        working-directory: library-repository

      - name: Publish library
        run: ./gradlew publish
        working-directory: library-repository
        env:
          mavenRepo: ${{ github.workspace }}/repos

      - name: Update repository
        run: |
          git config --global user.name "BlazerBot 7617"
          git config --global user.email "188250476+blazerbot-7617[bot]@users.noreply.github.com"
          git add repos/.
          git commit -m "Upgrading ${{ github.event.client_payload.libraryName }} to ${{ github.event.client_payload.releaseVersion }}"
          git push

      - name: Upload repository as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: repos/

  deploy:
    needs: update

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

