name: Update vendordep

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ inputs.releaseVersion }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Clone library repository
        run: |
          gh repo clone roboblazers7617/ButtonBoxLib

      - name: Build library
        run: ./gradlew build
        working-directory: ButtonBoxLib

      - name: Publish library
        run: ./gradlew publish
        working-directory: ButtonBoxLib
        env:
          mavenRepo: ${{ github.workspace }}/repos

      - name: Update repository
        run: |
          git config --global user.name "blazerbot-7617[bot]"
          git config --global user.email "188250476+blazerbot-7617[bot]@users.noreply.github.com"
          git add repos/.
          git commit -m "Upgrading ButtonBoxLib to ${{ inputs.releaseVersion }}"
          git push
